# Generated by Django 4.0 on 2021-12-30 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pillarplus', '0003_fileloader_form_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='googleform',
            name='form_name',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='pillarplus.formname'),
        ),
    ]
